### ISSUE TITLE
[New Video Request]: How much JavaScript is needed to learn React.js?

### ISSUE THREAD

**Issue by vikasganiga05** [atapas/youtube#20]
👋 Hey There,

You can request a video in the areas of,
- Web Development(JavaScript, React, CSS, HTML, many more)
- Jamstack
- Content Creation/Blogging
- Career

# Please provide the answer to the questions below to get started:

- Suggest a Topic Name
How much JavaScript is needed to learn React.js?

- What do you want to Learn(Please provide some pointers)?
The JavaScript concepts to learn before learning React.js. Sometimes people think one particular feature is provided by React, but instead it’s just modern JavaScript syntax.

- How soon do you need this video tutorial?(Give minimum a couple of weeks)
At your convenience.

- Do you want to see your name, social handle as a requester in the Video Description? (If yes, please mention the full name, social handle, etc.)
Vikas Ganiga | [twitter.com/vikasganiga05](https://twitter.com/vikasganiga05) | [github.com/vikasganiga05](https://github.com/vikasganiga05)

> Note: Please be polite while raising the request. The creator has all the rights to accept/reject a request. There is no strong commitment made by the creator to publish a requested video within any given time frame. But, will try as much as possible.

**Comment by atapas** [comment]
@vikasganiga05 

Thanks a lot for opening the issue. I have captured it in this video: https://www.youtube.com/watch?v=ODKIxaSMgpU

The above video also links several other videos on JS required to get started with React.

Also, I have captured it in greater detail here: https://www.freecodecamp.org/news/react-fundamentals-for-beginners/

I hope it helps.

**Comment by atapas** [comment]
I am closing this issue based on the above comment.

**Comment by vikasganiga05** [comment]
> @vikasganiga05
> 
> Thanks a lot for opening the issue. I have captured it in this video: https://www.youtube.com/watch?v=ODKIxaSMgpU
> 
> The above video also links several other videos on JS required to get started with React.
> 
> Also, I have captured it in greater detail here: https://www.freecodecamp.org/news/react-fundamentals-for-beginners/
> 
> I hope it helps.

Oh! sorry, I have not made research. I will not make this mistake in the future. Thanks! :pray:
