### ISSUE TITLE
[DOCS]: Update video request issue template(MD) to issue form(YML)

### ISSUE THREAD

**Issue by vikasganiga05** [atapas/youtube#21]
Hi @atapas , I updated the video request issue template to use the [Issue Form](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms#yaml-issue-form-template) instead of simple [Markdown](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms#markdown-issue-template). New, YAML configured issue forms enable maintainers to build structured forms with required fields and easy-to-follow steps so that they can capture every important detail. Click Here :point_right:  [To know more about Issue Forms](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms).

---

### The Issue Form look like this before submitting issue:
![screenshot-github com-2022 02 05-11_05_41](https://user-images.githubusercontent.com/74750414/152631129-164725f5-75ee-4b7b-bfe2-5efe9046a71c.png)

---

### After submitting the issue it look like this:
![screenshot-github com-2022 02 05-11_22_55](https://user-images.githubusercontent.com/74750414/152631254-97847330-d7f6-4bf9-a4fa-61af4b185c9a.png)

---

If you want to change anything! Let me know :slightly_smiling_face:

**Comment by vikasganiga05** [comment]
I like to work on this :+1:

**Comment by atapas** [comment]
Cool, idea. 😀

**Comment by atapas** [comment]
@vikasganiga05 Assigned to you, Go ahead

**Comment by vikasganiga05** [comment]
Thanks for assigning me this issue. Please review my changes in PR #22 .
