### ISSUE TITLE
Feature: update readme with video thumbnails and redirect links

### ISSUE THREAD

**Issue by Shreyas-SAS** [atapas/youtube#42]
hey, I would like to suggest an issue as a feature to work on during hactoberfest, 

Suggestion: It could be easier and better if we could add video or playlist thumbnails on the readme of this repositories with redirect link to youtube.
this would serve 2 purposes, increase traffic, create this repo more visually appealing.

can I work on this issue? @atapas

**Comment by atapas** [comment]
Hey @Shreyas-SAS I somehow missed seeing this. I am not sure if you are still interested in it.

**Comment by Shreyas-SAS** [comment]
No. I actually was interested in the task for hacktoberfest since I could not contribute long hours at the time. I wanted to make small contributions but, since there was no response from your side and even my contributions for your other repos weren't approved even till the end of hacktoberfest. I felt like it was the best thing that I did not invest more time in contributing to your repos. 

So, in short NO. I am no longer interested in the issue. You may close it. There is nothing to learn from it anyways.
